name: openair

description:
  "OpenAir is a free and open-source cross-platform podcast app that empowers you to
  explore and enjoy the vast world of podcasts."

publish_to: "none"

version: 0.14.40+24

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.4.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  convert: ^3.1.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.8.0+1
  file_picker: ^10.3.3
  flutter_dotenv: ^5.2.0
  flutter_localizations_plus: ^0.3.0
  flutter_riverpod: ^2.5.1
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  http: ^1.2.1
  icon_forest: ^1.1.8
  logger: ^2.3.0
  oauth2_client: ^4.2.0
  opml: ^0.4.0
  path: ^1.9.0
  path_provider: ^2.1.3
  path_to_regexp: ^0.4.0
  permission_handler: ^12.0.0+1
  shimmer: ^3.0.0
  theme_provider: ^0.6.0
  url_launcher: ^6.3.2
  webfeed_plus: ^1.1.2
  xml: ^6.5.0
  package_info_plus: ^8.3.1
  scheduled_timer: ^2.0.1
  supabase_flutter: ^2.10.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.3
  flutter_local_notifications: ^19.4.2
  window_manager: ^0.5.1
  flutter_html: ^3.0.0
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.9.2
  rename: ^3.1.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - locales/
    - assets/icons/icon.png
    - assets/icons/org.openair.podcast.svg
    - assets/images/github-white-logo.png
    - assets/images/github-black-logo.png
    - assets/images/google-white-logo.png
    - assets/images/google-black-logo.png
